### ISSUE TITLE
remove QT dependency

### ISSUE THREAD

**Issue by wolfv** [conda-forge/jupyter-feedstock#10]
I think it would be great if QT and qtconsole would be optional. 
It ends up downloading *a lot* of data that is unnecessary, most of the time. 

For me it pulls in:

```
    gst-plugins-base-1.14.5    |       h0935bb2_0         6.8 MB  conda-forge
    gstreamer-1.14.5           |       h36ae1b5_0         4.5 MB  conda-forge
    libclang-9.0.0             |       hc9558a2_1        22.2 MB  conda-forge
    libllvm9-9.0.0             |       hc9558a2_2        25.1 MB  conda-forge
    pyqt-5.12.3                |   py37hcca6a23_0         6.3 MB  conda-forge
    qt-5.12.5                  |       h0c104cb_0        99.0 MB  conda-forge
```

wouldn't it be nice to have a seperate package for the qtconsole?

**Comment by isuruf** [comment]
This came up in https://github.com/conda-forge/miniforge/issues/102 too.

**Comment by ocefpaf** [comment]
I would love to remove qt as much as possible but I'd like to hear from @minrk first.

That would break envs for qtconsole users installing just "jupyter" and I have no idea how many users of qtconsole are out there. (It was quite popular on Windows when it first came out, maybe not such much today?)

**Comment by jakirkham** [comment]
Agree on all points.

Also the addition of the notebook backed for matplotlib and the growth of the widget ecosystem has addressed a lot of the areas where Qt use to be needed.

**Comment by duncanmmacleod** [comment]
Resurrecting this a year on, could this be naively solved (or at least worked around) by shifting the requirement from `qtconsole` to `qtconsole-base`, which provides the `qtconsole` python library without bringing in `pyqt`?

**Comment by minrk** [comment]
Short answer: no objection to depending on qtconsole-base.

The Jupyter metapackage is meant to be 'all the jupyter things' i.e. notebook, qtconsole, etc. If all you want is the notebook, why not install `notebook`? But we set it up when qtconsole was at least as popular as the notebook, which isn't true anymore.

But I also understand it's weird that 'jupyter' isn't really a package, so people are going to install it anyway, and in 2022 excluding qtconsole (and jupyter-console) probably matches today's expectations more closely.

Removing qtconsole (and console) from the metapackage should probably be proprosed to [the metapackage itself](https://github.com/jupyter/jupyter/blob/master/setup.py#L28), rather than deviating the conda metapackage from the PyPI metapackage, and then update here to remove the dependency.

**Comment by rootsmusic** [comment]
Vote at https://github.com/jupyter/jupyter/issues/718
