### ISSUE TITLE
Path shared with jupyter_core

### ISSUE THREAD

**Issue by ceball** [conda-forge/jupyter-feedstock#4]
Hi

Not sure I'm in the right place to report this, or if it matters, but I happened to notice that jupyter and jupyter_core appear to share a path:

```
$ conda create --name=jclob python=3.6
$ conda activate jclob
$ conda config --set path_conflict prevent
$ conda install -c conda-forge jupyter
[...]
ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::jupyter_core-4.4.0-py_0, conda-forge::jupyter-1.0.0-py_1
  path: 'lib/python3.6/site-packages/jupyter.py'
If you'd like to proceed anyway, re-run the command with the `--clobber` flag.
.

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::jupyter_core-4.4.0-py_0, conda-forge::jupyter-1.0.0-py_1
  path: 'lib/python3.6/site-packages/__pycache__/jupyter.cpython-36.pyc'
If you'd like to proceed anyway, re-run the command with the `--clobber` flag.
.
```

**Comment by michaelkarlcoleman** [comment]
I ran into this, and was able to proceed by explicitly installing `jupyter` from the `anaconda` channel.  Apparently the `conda-forge` version is broken.  (or perhaps my repo has bit rot)

**Comment by xylar** [comment]
@ocefpaf and @minrk, I ran into this, too.  Do either of you know if this is a problem with the feedstock(s) or the packages themselves?  My guess is that the problem lies upstream.  

It seems a bit troubling to clobber files from `jupyter_core` with `jupyter`, potentially from different versions.

**Comment by xylar** [comment]
Okay, some more info on this.  The `jupyter.py` module was deleted from the `jupyter` repo awhile back:
https://github.com/jupyter/jupyter/pull/198
The `jupyter` package became a metapackage and has not been updated on pypi since then, see:
https://github.com/jupyter/jupyter_core/issues/85

So I believe the solution is to make this recipe a pure metapackage, just as https://github.com/jupyter/jupyter has done and as suggested in the second issue above.  I will make a PR to do this.
